import Phaser from 'phaser';
type P={x:number;y:number};
export class DrawingSystem{
 private points:P[]=[];private localPoints:P[]=[];private bodies:MatterJS.BodyType[]=[];private supports=0;private drawing=false;private locked=false;private g:Phaser.GameObjects.Graphics;private physicalG:Phaser.GameObjects.Graphics;used=0;onRelease?:()=>void;
 private readonly pointerDown=(p:Phaser.Input.Pointer)=>this.start(p);private readonly pointerMove=(p:Phaser.Input.Pointer)=>this.move(p);private readonly pointerUp=()=>this.finish();
 constructor(private scene:Phaser.Scene,public maxInk:number,private solids:Phaser.Geom.Rectangle[]){this.g=scene.add.graphics().setDepth(8);this.physicalG=scene.add.graphics().setDepth(7);scene.input.on('pointerdown',this.pointerDown);scene.input.on('pointermove',this.pointerMove);scene.input.on('pointerup',this.pointerUp)}
 private valid(x:number,y:number){return x>8&&x<382&&y>88&&y<790&&!this.solids.some(r=>Phaser.Geom.Rectangle.Contains(r,x,y))}
 private start(p:Phaser.Input.Pointer){if(this.locked||!this.valid(p.x,p.y))return;this.drawing=true;this.points=[{x:p.x,y:p.y}];this.used=0}
 private move(p:Phaser.Input.Pointer){if(!this.drawing)return;const q=this.points.at(-1)!;const d=Math.hypot(p.x-q.x,p.y-q.y);if(d<9)return;if(this.used+d>this.maxInk||!this.valid(p.x,p.y)){if(this.used+d>this.maxInk)this.finish();return}this.points.push({x:p.x,y:p.y});this.used+=d;this.render()}
 private render(){this.g.clear().lineStyle(11,0x5148d9,1).beginPath().moveTo(this.points[0].x,this.points[0].y);for(let i=1;i<this.points.length;i++){const a=this.points[i-1],b=this.points[i];this.g.lineTo((a.x+b.x)/2,(a.y+b.y)/2)}this.g.lineTo(this.points.at(-1)!.x,this.points.at(-1)!.y).strokePath()}
 private nearSolid(p:P){return this.solids.some(r=>p.x>=r.x-24&&p.x<=r.right+24&&p.y>=r.y-24&&p.y<=r.bottom+24)||p.x<20||p.x>370}
 private finish(){if(!this.drawing)return;this.drawing=false;if(this.points.length<2){this.points=[];this.g.clear();return}this.locked=true;const parts:MatterJS.BodyType[]=[];for(let i=1;i<this.points.length;i++){const a=this.points[i-1],b=this.points[i],len=Math.hypot(b.x-a.x,b.y-a.y),ang=Math.atan2(b.y-a.y,b.x-a.x);parts.push(this.scene.matter.bodies.rectangle((a.x+b.x)/2,(a.y+b.y)/2,len+5,12,{angle:ang,chamfer:{radius:6}}))}this.supports=[this.points[0],this.points.at(-1)!].filter(p=>this.nearSolid(p)).length;const compound=this.scene.matter.body.create({parts,label:'shield',isStatic:this.supports===2,friction:.95,frictionStatic:1,frictionAir:.045,restitution:.01,density:.0016,sleepThreshold:35});this.scene.matter.world.add(compound);this.bodies=[compound];this.localPoints=this.points.map(p=>({x:p.x-compound.position.x,y:p.y-compound.position.y}));this.g.clear();this.update();this.onRelease?.()}
 pushFromBee(bee:MatterJS.BodyType,shield:MatterJS.BodyType){if(this.supports===2)return;const dx=shield.position.x-bee.position.x,dy=shield.position.y-bee.position.y,d=Math.max(1,Math.hypot(dx,dy)),power=shield.mass*.00004;this.scene.matter.body.applyForce(shield,shield.position,{x:dx/d*power,y:(dy/d-.15)*power})}
 update(){if(!this.locked||!this.bodies.length)return;const body=this.bodies[0];if(!body.isStatic){const v=body.velocity,vm=Math.hypot(v.x,v.y);if(vm>5)this.scene.matter.body.setVelocity(body,{x:v.x/vm*5,y:v.y/vm*5});if(Math.abs(body.angularVelocity)>.06)this.scene.matter.body.setAngularVelocity(body,Math.sign(body.angularVelocity)*.06)}const cos=Math.cos(body.angle),sin=Math.sin(body.angle),world=this.localPoints.map(p=>({x:body.position.x+p.x*cos-p.y*sin,y:body.position.y+p.x*sin+p.y*cos}));this.physicalG.clear().lineStyle(13,0x5148d9,1).beginPath().moveTo(world[0].x,world[0].y);for(let i=1;i<world.length;i++){const a=world[i-1],b=world[i];this.physicalG.lineTo((a.x+b.x)/2,(a.y+b.y)/2)}this.physicalG.lineTo(world.at(-1)!.x,world.at(-1)!.y).strokePath()}
 destroy(){this.scene.input.off('pointerdown',this.pointerDown);this.scene.input.off('pointermove',this.pointerMove);this.scene.input.off('pointerup',this.pointerUp);this.bodies=[];this.localPoints=[];this.supports=0}
}
