import Phaser from 'phaser';
import {COLORS,W,H} from '../config/constants';import {getLevel} from '../levels';import type {LevelData} from '../levels/types';
import {Dog} from '../entities/Dog';import {Bee} from '../entities/Bee';import {DrawingSystem} from '../systems/DrawingSystem';import {GameHUD} from '../ui/GameHUD';import {SaveManager} from '../systems/SaveManager';import {audio} from '../systems/AudioManager';
export class GameScene extends Phaser.Scene{
 private dataDef!:LevelData;private dog!:Dog;private bees:Bee[]=[];private draw!:DrawingSystem;private hud!:GameHUD;private started=false;private ended=false;private paused=false;private pausedAt=0;private remaining=0;private startAt=0;private rockViews:{body:MatterJS.BodyType,g:Phaser.GameObjects.Graphics,r:number}[]=[];
 constructor(){super('Game')}
 init(data:{level?:number}){this.dataDef=getLevel(data.level||1);this.bees=[];this.rockViews=[];this.started=false;this.ended=false;this.paused=false;this.pausedAt=0;this.startAt=0;this.remaining=this.dataDef.survivalTime}
 create(){
  this.matter.world.resume();this.drawWorld();this.matter.world.setBounds(0,84,W,H-84,40,true,true,false);
  const solids:Phaser.Geom.Rectangle[]=[],terrain=this.terrainColors();if(this.dataDef.liquid)this.drawLiquid(this.dataDef.liquid);
  for(const p of [...this.dataDef.platforms,...(this.dataDef.walls||[])]){const angle=p.angle||0;this.matter.add.rectangle(p.x,p.y,p.width,p.height,{isStatic:true,label:'solid',angle});const boundsWidth=angle?Math.abs(p.width*Math.cos(angle))+Math.abs(p.height*Math.sin(angle)):p.width,boundsHeight=angle?Math.abs(p.width*Math.sin(angle))+Math.abs(p.height*Math.cos(angle)):p.height;solids.push(new Phaser.Geom.Rectangle(p.x-boundsWidth/2,p.y-boundsHeight/2,boundsWidth,boundsHeight));this.add.rectangle(p.x,p.y,p.width,p.height,terrain.fill).setStrokeStyle(5,terrain.edge).setRotation(angle)}
  for(const s of this.dataDef.spikes||[])this.drawSpikes(s.x,s.y,s.width);for(const h of this.dataDef.hives)this.drawHive(h.x,h.y);for(const r of this.dataDef.rocks||[])this.addRock(r.x,r.y,r.r);
  this.dog=new Dog(this,this.dataDef.player.x,this.dataDef.player.y);this.draw=new DrawingSystem(this,this.dataDef.maxInk,solids);this.draw.onRelease=()=>this.beginAttack();this.hud=new GameHUD(this,this.dataDef.id,this.dataDef.worldName,this.dataDef.difficulty,()=>this.scene.start('Menu'),()=>this.scene.restart({level:this.dataDef.id}),()=>this.togglePause());
  if(this.dataDef.id===1&&!SaveManager.load().tutorialCompleted)this.tutorial();else if(this.dataDef.strategy)this.strategyHint();
  this.matter.world.on('collisionstart',(ev:Phaser.Physics.Matter.Events.CollisionStartEvent)=>this.handleCollisions(ev,true));this.matter.world.on('collisionactive',(ev:Phaser.Physics.Matter.Events.CollisionActiveEvent)=>this.handleCollisions(ev,false));this.events.once('shutdown',()=>this.cleanup())
 }
 private terrainColors(){return this.dataDef.theme==='meadow'?{fill:COLORS.dirt,edge:COLORS.ground}:this.dataDef.theme==='canyon'?{fill:0xa95f38,edge:0xe6a14b}:this.dataDef.theme==='sky'?{fill:0x6989a8,edge:0xd9f5ff}:this.dataDef.theme==='volcano'?{fill:0x592f35,edge:0xff7043}:{fill:0x38405f,edge:0x7f8bc9}}
 private drawWorld(){const theme=this.dataDef.theme,g=this.add.graphics();if(theme==='meadow'){this.cameras.main.setBackgroundColor(0xdff4ff);g.fillStyle(0xffffff,.75).fillEllipse(75,170,105,35).fillEllipse(320,260,130,42);g.fillStyle(0xffd85a,.9).fillCircle(330,135,34)}else if(theme==='canyon'){this.cameras.main.setBackgroundColor(0xffddb0);g.fillStyle(0xe9a760,.45).fillCircle(45,200,90).fillCircle(345,350,125);g.fillStyle(0xb9583c,.55).fillTriangle(0,700,95,385,180,700).fillTriangle(190,700,300,420,390,700)}else if(theme==='sky'){this.cameras.main.setBackgroundColor(0xbfefff);g.fillStyle(0xffffff,.75).fillEllipse(70,180,135,38).fillEllipse(315,310,150,45).fillEllipse(180,700,190,42)}else if(theme==='volcano'){this.cameras.main.setBackgroundColor(0x3b243d);g.fillStyle(0xff6b35,.25).fillCircle(35,690,170).fillCircle(365,720,140);g.fillStyle(0xffd166,.85);for(const p of [[40,170],[330,135],[285,410],[95,360]])g.fillCircle(p[0],p[1],2)}else{this.cameras.main.setBackgroundColor(0x242b4f);g.fillStyle(0xf6f0c7,.9).fillCircle(325,145,35);g.fillStyle(0x44517d,.8).fillCircle(338,135,35);g.fillStyle(0xffffff,.75);for(const p of [[45,145],[115,220],[260,190],[345,330],[75,390],[285,470]])g.fillCircle(p[0],p[1],2)}}
 private drawHive(x:number,y:number){const g=this.add.graphics().setDepth(2);g.fillStyle(0xe39a2e).fillEllipse(x,y,61,68);g.lineStyle(5,0xb96a25);for(let i=-2;i<=2;i++)g.lineBetween(x-24,y+i*10,x+24,y+i*10);g.fillStyle(0x5c3924).fillCircle(x,y+17,10)}
  private drawSpikes(x:number,y:number,width:number){const count=Math.floor(width/20),g=this.add.graphics();for(let i=0;i<count;i++){const px=x-width/2+i*20;g.fillStyle(0xe65d5d).fillTriangle(px,y+12,px+10,y-18,px+20,y+12)}this.matter.add.rectangle(x,y,width,28,{isStatic:true,isSensor:true,label:'spike'})}
 private drawLiquid(type:'water'|'lava'){const color=type==='lava'?0xff542e:0x38cde0,g=this.add.graphics().setDepth(1);g.fillStyle(color,.95).fillRect(0,782,W,62);g.lineStyle(5,type==='lava'?0xffca3a:0xb8fbff);for(let x=-10;x<W;x+=24)g.beginPath().arc(x,782,12,Math.PI,Math.PI*2).strokePath();this.matter.add.rectangle(W/2,817,W,54,{isStatic:true,isSensor:true,label:'liquid'})}
 private handleCollisions(ev:Phaser.Physics.Matter.Events.CollisionStartEvent|Phaser.Physics.Matter.Events.CollisionActiveEvent,canLose:boolean){for(const pair of ev.pairs){const a=pair.bodyA.parent||pair.bodyA,b=pair.bodyB.parent||pair.bodyB,labels=[a.label,b.label];if(canLose&&labels.includes('dog')&&(labels.includes('bee')||labels.includes('spike')||labels.includes('rock')||labels.includes('liquid')))this.finish(false);if(labels.includes('bee')&&labels.includes('shield')){const bee=a.label==='bee'?a:b,shield=a.label==='shield'?a:b;this.bees.find(item=>item.body===bee)?.hitShield();this.draw.pushFromBee(bee,shield)}}}
 private addRock(x:number,y:number,r:number){const body=this.matter.add.circle(x,y,r,{label:'rock',density:.008,friction:.8,restitution:.1});this.rockViews.push({body,g:this.add.graphics().setDepth(3),r})}
 private tutorial(){const t=this.add.text(W/2,108,this.dataDef.hint!,{fontFamily:'Arial',fontSize:'17px',fontStyle:'bold',color:'#5148d9',backgroundColor:'#ffffff',padding:{x:12,y:8}}).setOrigin(.5).setDepth(25),finger=this.add.text(80,570,'☝',{fontSize:'42px'}).setDepth(25);this.tweens.add({targets:finger,x:310,y:570,duration:1500,yoyo:true,repeat:2,onComplete:()=>{t.destroy();finger.destroy()}})}
 private strategyHint(){const t=this.add.text(W/2,108,this.dataDef.strategy!,{fontFamily:'Arial',fontSize:'14px',fontStyle:'bold',color:'#5148d9',backgroundColor:'#ffffff',padding:{x:11,y:7}}).setOrigin(.5).setDepth(25);this.tweens.add({targets:t,alpha:0,delay:2200,duration:500,onComplete:()=>t.destroy()})}
 private beginAttack(){if(this.started)return;this.started=true;this.startAt=this.time.now;this.dog.setState('scared');audio.beep(280,.12,'sawtooth');for(const hive of this.dataDef.hives)for(let i=0;i<hive.beeCount;i++)this.time.delayedCall(i*hive.spawnDelay,()=>{if(!this.ended)this.bees.push(new Bee(this,hive.x+(Math.random()-.5)*20,hive.y+(Math.random()-.5)*18,hive.beeType))})}
 update(time:number){this.dog.update();this.draw.update();if(!this.paused)for(const b of this.bees)b.update(this.dog.body.position.x,this.dog.body.position.y,time,this.bees);for(const rv of this.rockViews){const p=rv.body.position;rv.g.clear().fillStyle(0x758093).fillCircle(p.x,p.y,rv.r).lineStyle(4,0x596474).strokeCircle(p.x,p.y,rv.r).fillStyle(0x929baa).fillCircle(p.x-rv.r*.25,p.y-rv.r*.2,rv.r*.18)}this.hud.updateInk(1-this.draw.used/this.dataDef.maxInk);if(this.started&&!this.ended&&!this.paused){this.remaining=this.dataDef.survivalTime-(time-this.startAt)/1000;this.hud.setTimer(this.remaining);if(this.remaining<=0)this.finish(true)}if(this.dog.body.position.y>H+40)this.finish(false)}
 private finish(win:boolean){if(this.ended)return;this.ended=true;this.dog.setState(win?'celebrating':'hurt');navigator.vibrate?.(win?[30,40,30]:80);if(win){this.matter.world.pause();const ratio=this.draw.used/this.dataDef.maxInk,stars=ratio<=this.dataDef.starThresholds.threeStars?3:ratio<=this.dataDef.starThresholds.twoStars?2:1;SaveManager.complete(this.dataDef.id,stars);audio.beep(760,.2);this.time.delayedCall(350,()=>this.scene.start('Win',{level:this.dataDef.id,stars,used:Math.round(ratio*100)}))}else{audio.beep(130,.28,'square');queueMicrotask(()=>{if(this.scene.isActive())this.scene.start('Lose',{level:this.dataDef.id})})}}
 private togglePause(){if(this.ended)return;this.paused=!this.paused;if(this.paused){this.pausedAt=this.time.now;this.matter.world.pause();this.add.text(W/2,H/2,'PAUSED',{fontFamily:'Arial',fontSize:'36px',fontStyle:'bold',color:'#ffffff',backgroundColor:'#253449',padding:{x:22,y:14}}).setOrigin(.5).setDepth(40).setName('pauseLabel')}else{this.startAt+=this.time.now-this.pausedAt;this.matter.world.resume();this.children.getByName('pauseLabel')?.destroy()}}
 private cleanup(){this.draw?.destroy();this.bees=[];this.rockViews=[]}
}
